export const supportedSites = [
    "www.openrec.tv",
    "abema.tv",
    "live2.nicovideo.jp",
    "cas.nicovideo.jp",
    "gyao.yahoo.co.jp",
    "www.dmm.com",
    "www.dmm.co.jp",
    "www.360ch.tv",
    "www.sonymusic.co.jp",
    "twitcasting.tv",
    "www.showroom-live.com",
    "hibiki-radio.jp",
    "www.youtube.com",
    "nogidoga.com",
    "stagecrowd.live",
    "spwn.jp",
    "live.bilibili.com"
];
